# Site settings
title: Projects
description: > # this means to ignore newlines until "baseurl:"
  Fuzzy Bearings Projects
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://projects.fuzzybearings.com/" # the base hostname & protocol for your site
twitter_username: fuzzybearings
github_username:  FuzzyBearings

permalink: /:year/:month/:day/:title.html

# Build settings
markdown: kramdown

# User added
excludes: go.sh
